### ISSUE TITLE
[Design] Ledger/Wallet backwards compatibility

### ISSUE THREAD

**Issue by r4mmer** [HathorNetwork/hathor-ledger-app#42]
# Summary
[summary]: #summary

The addition of custom tokens only has one feature that is not backwards compatible, change outputs.
Since the current protocol allows only one and we now need multiple, we cannot have the the old wallet version working with the new Ledger version and vice-versa.
This aims to solve this backwards compatibility issue.

# Motivation
[motivation]: #motivation

Solving compatibility issues between versions of Ledger and Hathor wallet that have risen from the recent custom tokens addition.

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation

The current protocol expects "have change" as a boolean followed by the change output index (current protocol reference [here](https://github.com/HathorNetwork/hathor-ledger-app/blob/master/doc/COMMANDS.md#command-3) and [here](https://github.com/HathorNetwork/hathor-ledger-app/blob/master/doc/TRANSACTION.md#change-info))
The custom token change output protocol expects a list of change outputs.

### New wallet version with old Ledger version

The new wallet cannot send custom tokens with the old Ledger, but we should at least allow sending HTR.
This means we should check the version and if it's a version pre-custom tokens we should send the change info as the old protocol.

We can split the Ledger features in 3 groups:
1. features unchanged from the previous version
1. send custom tokens (with multiple change)
1. new features only for custom tokens

The unchanged features can be ignored in this context.

Sending tokens has changed drastically but it is backwards compatible.
We shouldn't allow for custom tokens to be added on a transaction if the wallet identifies an old Ledger version.

The new features will be used in many places and should be conitionally used based on the Ledger version.
- Check token signatures on startup
- Show reset token signatures button on settings
- Show sign custom token with Ledger button

### New Ledger version with old wallet version

The new Ledger version is still backwards compatible with every feature on the old wallet except the change output info.
This means that if we have a way to detect that it is from the old protocol we can read as the old protocol.
This is why we are adding a version byte to the transaction data.

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation

### New wallet version with old Ledger version

We should save the Ledger version of the current device on storage.
We can have an async method `isLedgerCustomTokenAllowed` to return a boolean if the Ledger version saved is greater than the last Ledger version.
This method is an util that can be used to branch each case defined on the guide level.

If (for any reason) the Ledger version is not saved on the storage when this method is called it can request the version from the device and return a promise to check the response.

### New Ledger version with old wallet version

The old protocol starts with a byte `A___ BBBB` where `A` indicates the existence of a change output and `B` is the output index as an unsigned 4 bit integer.
The new protocol will have a version byte and we should choose this version byte such as never to coincide with a change output from the old protocol, this simply means we should have the first bit 0.

The first version should be 1 (`0000 0001`) and we can read the first byte to check if we are dealing with an old wallet version:
- first bit == 1: old wallet with change
- first bit == 0:
    - first byte == 0: old wallet and no change
    - first byte == 1: new wallet

The new protocol of change information will be:
```
change_info = version byte(1) + len_change_outputs(1) + list_change_outputs(var)

change_output = output_index(1) + bip32_path_len(1) + bip32_path (4*bip32_path_len)
```

# Drawbacks
[drawbacks]: #drawbacks

- We will have implementations of both the new and old protocols on the ledger and the wallet.
- The new wallet will need to check the version before allowing users to add custom tokens.

# Future possibilities
[future-possibilities]: #future-possibilities

We could make a Hathor-Ledger js lib to handle serialization and transport.
We could even have multiple versions (of the protocol) on the lib so that we could use the correct one depending on the version.

This is not a novel idea since Ledger has examples of this lib for other coins like [Bitcoin](https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-app-btc) and [Ethereum](https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-app-eth).
This also makes it easier to add Ledger to other HTR wallets.

**Comment by luislhl** [comment]
> The current protocol expects "have change" as a boolean followed by the change output index

I think it would help the reviewers if you added a link to https://github.com/HathorNetwork/hathor-ledger-app/blob/master/doc/COMMANDS.md#command-3

> We should save the Ledger version of the current device on storage and when we are serializing the transaction we can have a simple branching for the old versions.

Should we also show an alert suggesting that the user updates his Ledger app?

Only if this is something that won't generate problems, of course, like if we release the Hathor Wallet before the new version of the Ledger app is approved by Ledger (in which case people would be unable to update)

> New Ledger version with old wallet version

Maybe we could have an alert for the user in this case as well. We could make the wallet detect if the Ledger app version is greater than what it supports, and show an alert asking to be upgraded.

Maybe we could even have a Protocol Version (similar to an API version), that we would bump when there are backwards-incompatible changes, and use this in the alerting mechanism

But maybe this needs a different design.

**Comment by r4mmer** [comment]
> Should we also show an alert suggesting that the user updates his Ledger app?

This can be done when there is a new Ledger version for the user to upgrade to.
Like you said, it could take some time until the new Ledger version is available and until then this design is to provide compatibility so the user can upgrade his wallet without losing any features.

> Maybe we could have an alert for the user in this case as well. We could make the wallet detect if the Ledger app version is greater than what it supports, and show an alert asking to be upgraded.

This is actually already being done, we will have a lower and upper limit on Ledger versions, but since we didn't have this on the "old wallet" it doesn't know which ledger version it supports.

> Maybe we could even have a Protocol Version (similar to an API version), that we would bump when there are backwards-incompatible changes, and use this in the alerting mechanism
> But maybe this needs a different design.

I thought the same thing, that's why I added the entry on the "future possibilities" section.
The lib could check the version and switch to an implementation of the supported protocol version.
And the wallet does not need to know how the information is being serialized, only when some functionality is missing from the Ledger, which can be done with exceptions.

But I also think this app needs it's own design since it can be very complicated.

**Comment by pedroferreira1** [comment]
I like the ledger solution to keep compatibilities. I just think we should describe better how we will handle this in the wallet.

We currently have 3 different "features" that depend on the new ledger version (i) send custom tokens, (ii) verify tokens when adding them, (iii) check tokens signatures on startup. We are going to run some checks in all of them, correct? How is it going to be? Create a method `isCustomTokenAllowed`? Or  create a method `checkVersion` like `if version > X and version < Y: return true` and each place we know the needed versions.

This is the only piece I'm missing in this design, I don't know how we are going to handle this in the wallet.

**Comment by r4mmer** [comment]
> I don't know how we are going to handle this in the wallet.

Explained it better, for adding custom tokens on a transaction we could just let the send method fail but the user wouldn't understand why so I'm keeping the alert modal when trying to add custom tokens, this way the wallet won't change any functionality from the old version.

**Comment by pedroferreira1** [comment]
For me it's good, approved.

**Comment by luislhl** [comment]
:heavy_check_mark:
